=== morbitz/EUO/Protocolo/UO Packet Guide/packets.dtd
<!ENTITY % From "(server|client|both|unknown)">
<!ENTITY % Type "(byte|word|dword|char|uchar|sbyte|loop|endloop|qword)">

<!ELEMENT Packets (Packet*)>

<!ELEMENT Packet (Name,Desc,Data*,Note?)>
<!ATTLIST Packet
  id        CDATA       #REQUIRED
  size      CDATA       #REQUIRED
  from      %From;      #REQUIRED
  >

<!ELEMENT Name ANY>

<!ELEMENT Desc ANY>

<!ELEMENT Note ANY>

<!ELEMENT Data ANY>
<!ATTLIST Data
  type      %Type;      #REQUIRED
  amount    CDATA       #IMPLIED
  >

=== morbitz/EUO/Protocolo/UO Packet Guide/UO Packet Guide.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="design00.htm" ?>
<!DOCTYPE Packets SYSTEM "packets.dtd">

<Packets>
    <Packet id="00" size="104" from="client" >
        <Name>Character Creation</Name>
        <Desc>Create a new character (2D clients).</Desc>
        <Data type="byte">ID (00)</Data>
        <Data type="dword">0xEDEDEDED</Data>
        <Data type="dword">0xFFFFFFFF</Data>
        <Data type="byte">0x00</Data>
        <Data type="char" amount="30">Character Name</Data>
        <Data type="word">0x00</Data>
        <Data type="dword">Client Flags (0x01 = Felucca Facet, 0x02 = Trammel Facet, 0x04 = Ilshenar Facet, 0x08 = Malas Facet, 0x10 = Tokuno Facet, 0x20 = Ter Mur Facet, 0x40 = UO3D Client, 0x80 = Reserved for Facet06, 0x100 = UOTD)</Data>
        <Data type="dword">1</Data>
        <Data type="dword">Client Login Count</Data>
        <Data type="byte">Profession</Data>
        <Data type="byte" amount="15">0x00</Data>
        <Data type="byte">Gender and Race: (0x00 = human male, 0x01 = human female, 0x02 = human male, 0x03 = human female, 0x04 = elf male, 0x05 = elf female, 0x06 = gargoyle male, 0x07 = gargoyle female)</Data>
        <Data type="byte">Strength</Data>
        <Data type="byte">Dexterity</Data>
        <Data type="byte">Intelligence</Data>
        <Data type="byte">Skill 1</Data>
        <Data type="byte">Skill 1 Amount</Data>
        <Data type="byte">Skill 2</Data>
        <Data type="byte">Skill 2 Amount</Data>
        <Data type="byte">Skill 3</Data>
        <Data type="byte">Skill 3 Amount</Data>
        <Data type="word">Skin Color</Data>
        <Data type="word">Hair Style</Data>
        <Data type="word">Hair Color</Data>
        <Data type="word">Beard Style</Data>
        <Data type="word">Beard Color</Data>
        <Data type="byte">Shard Index</Data>
        <Data type="byte">Starting City</Data>
        <Data type="dword">Character Slot</Data>
        <Data type="dword">Client IP</Data>
        <Data type="word">Shirt Color</Data>
        <Data type="word">Pants Color</Data>
    </Packet>
    <Packet id="01" size="5" from="client">
        <Name>Logout</Name>
        <Desc>Character returns to main menu from character select menu.</Desc>
        <Data type="byte">ID (01)</Data>
        <Data type="dword">0xFFFFFFFF</Data>
    </Packet>
    <Packet id="02" size="7" from="client">
        <Name>Movement Request</Name>
        <Desc>Ask the server if we can walk.</Desc>
        <Data type="byte">ID (02)</Data>
        <Data type="byte">Direction (0x00 = North, 0x01 = Right, 0x02 = East, 0x03 = Down, 0x04 = South, 0x05 = Left, 0x06 = West, 0x07 = Up, 0x80 = Running)</Data>
        <Data type="byte">Sequence Number</Data>
        <Data type="dword">Fastwalk Prevention Key</Data>
    </Packet>
    <Packet id="03" size="-1" from="client">
        <Name>Ascii Speech</Name>
        <Desc>Send ascii speech to the server.</Desc>
        <Data type="byte">ID (03)</Data>
        <Data type="word">Size of Packet</Data>
        <Data type="byte">Mode (0x00 = say, 0x01 = system, 0x02 = emote, 0x06 = label, 0x07 = focus, 0x08 = whipser, 0x09 = yell, 0x10 = spell, 0x13 = guild, 0x14 = alliance, 0x15 = GM, 0xC0 = encoded commands)</Data>
        <Data type="word">Text Color</Data>
        <Data type="word">Font</Data>
        <Data type="char" amount="*">Text</Data>
    </Packet>
    <Packet id="04" size="2" from="client">
        <Name>Toggle God Mode Request</Name>
        <Desc>God Mode Request Packet.</Desc>
        <Data type="byte">ID (04)</Data>
        <Data type="byte">God Mode On/Off</Data>
    </Packet>
    <Packet id="05" size="5" from="client">
        <Name>Attack Request</Name>
        <Desc>Send attack request to server.</Desc>
        <Data type="byte">ID (05)</Data>
        <Data type="dword">Combatant Serial</Data>
        <Note>If Last Attack and combatant is null, send owner's serial.</Note>
    </Packet>
    <Packet id="06" size="5" from="client">
        <Name>Use Request</Name>
        <Desc>Ask the server if we can use an object (double click).</Desc>
        <Data type="byte">ID (06)</Data>
        <Data type="dword">Item Serial</Data>
    </Packet>
    <Packet id="07" size="7" from="client">
        <Name>Lift Request</Name>
        <Desc>Ask the server if we can lift an object.</Desc>
        <Data type="byte">ID (07)</Data>
        <Data type="dword">Item Serial</Data>
        <Data type="word">Item Amount</Data>
    </Packet>
    <Packet id="08" size="15" from="client">
        <Name>Drop Request</Name>
        <Desc>Ask the server if we can lift an object.</Desc>
        <Data type="byte">ID (08)</Data>
        <Data type="dword">Item Serial</Data>
        <Data type="word">Item X</Data>
        <Data type="word">Item Y</Data>
        <Data type="sbyte">Item Z</Data>
        <Data type="byte">Grid Location</Data>
        <Data type="dword">Container Serial (-1 for ground)</Data>
        <Note>Grid Location only since 6.0.1.7 2D and 2.45.5.6 UO3D</Note>
    </Packet>
    <Packet id="09" size="5" from="client">
        <Name>Look Request</Name>
        <Desc>Ask the server to look at an item (single click).</Desc>
        <Data type="byte">ID (09)</Data>
        <Data type="dword">Item Serial</Data>
    </Packet>
    <Packet id="0A" size="11" from="client">
        <Name>Edit Item</Name>
        <Desc>Edit npcs, dynamic and static items.</Desc>
        <Data type="byte">ID (0A)</Data>
        <Data type="byte">Type</Data>
        <Data type="word">Item X</Data>
        <Data type="word">Item Y</Data>
        <Data type="word">Item ID</Data>
        <Data type="sbyte">Item Z</Data>
        <Data type="word">Item Hue</Data>
        <Note>Types are: 0x04 = Dynamic Item, 0x07 = NPC, 0x0A = Static Item, 0x0B = Add New Static Item (Force Static Creation)</Note>
    </Packet>
    <Packet id="0A.06" size="11" from="client">
        <Name>Hack Mover Request</Name>
        <Desc>Hack Mover Request Packet.</Desc>
        <Data type="byte">ID (0A)</Data>
        <Data type="byte">0x06</Data>
        <Data type="byte">0x00</Data>
        <Data type="byte">OnOff (0x00 = off, 0x01 = on)</Data>
        <Data type="byte" amount="7">Ox00</Data>
    </Packet>  
    <Packet id="0B" size="7" from="server">
        <Name>Damage Packet</Name>
        <Desc>Damage Packet.</Desc>
        <Data type="byte">ID (0B)</Data>
        <Data type="dword">Serial</Data>
        <Data type="word">Damage Amount</Data>
        <Note>Before 4.0.7a 2D client, was an Edit Area packet</Note>
    </Packet>
    <Packet id="0C" size="-1" from="unknown">
        <Name>Edit TileData</Name>
        <Desc>Edit TileData Packet.</Desc>
        <Data type="byte">ID (0C)</Data>
        <Data type="word">Packet Size</Data>
        <Data type="byte" amount="*">Unknown Data</Data>
        <Note>God Client packet, unknown data</Note>
    </Packet>
    <Packet id="0D" size="3" from="unknown">
        <Name>Edit NPC Data</Name>
        <Desc>Edit NPC Data Packet.</Desc>
        <Data type="byte">ID (0D)</Data>
        <Data type="byte" amount="2">Unknown</Data>
        <Note>God Client packet, unknown data</Note>
    </Packet>
    <Packet id="0E" size="-1" from="unknown">
        <Name>Edit Template Data</Name>
        <Desc>Edit Template Data Packet.</Desc>
        <Data type="byte">ID (0E)</Data>
        <Data type="word">Packet Size</Data>
        <Data type="byte" amount="*">Unknown</Data>
        <Note>God Client packet, unknown data</Note>
    </Packet>
    <Packet id="0F" size="61" from="unknown">
        <Name>Paperdoll</Name>
        <Desc>Paperdoll.</Desc>
        <Data type="byte">ID (0F)</Data>
        <Data type="byte" amount="60">Unknown</Data>
        <Note>God Client packet, unknown data</Note>
    </Packet>
    <Packet id="10" size="215" from="unknown">
        <Name>Edit Hue Data</Name>
        <Desc>Edit Hue Data Packet.</Desc>
        <Data type="byte">ID (10)</Data>
        <Data type="byte" amount="214">Unknown</Data>
        <Note>God Client packet, unknown data</Note>
    </Packet>
    <Packet id="11" size="-1" from="server">
        <Name>Mobile Status</Name>
        <Desc>Status of character.</Desc>
        <Data type="byte">ID (11)</Data>
        <Data type="word">Packet Size</Data>
        <Data type="dword">Serial</Data>
        <Data type="char" amount="30">Name</Data>
        <Data type="word">Hit Points</Data>
        <Data type="word">Maximum Hit Points</Data>
        <Data type="byte">Allow Name Change (0x01 = yes, 0x00 = no)</Data>
        <Data type="byte">Supported Features (0x02 = T2A attributes, 0x03 = Renaissance attributes, 0x04 = AOS attributes, 0x05 = ML attributes, 0x06 = KR attributes)</Data>
        <Data type="byte">Gender</Data>
        <Data type="word">Strength</Data>
        <Data type="word">Dexterity</Data>
        <Data type="word">Intelligence</Data>
        <Data type="word">Stamina</Data>
        <Data type="word">Maximum Stamina</Data>
        <Data type="word">Mana</Data>
        <Data type="word">Maximum Mana</Data>
        <Data type="dword">Gold</Data>
        <Data type="word">Armor Rating (Physical Resistance since AOS)</Data>
        <Data type="word">Weight</Data>
        <Data type="word">Maximum Weight (ML attribute)</Data>
        <Data type="byte">Race (0x01 = Human, 0x02 = Elf, 0x03 = Gargoyle) (ML attribute)</Data>
        <Data type="word">Stat Cap (T2A attribute)</Data>
        <Data type="byte">Followers (Renaissance attribute)</Data>
        <Data type="byte">Maximum Followers (Renaissance attribute)</Data>
        <Data type="word">Fire Resistance (AOS attribute)</Data>
        <Data type="word">Cold Resistance (AOS attribute)</Data>
        <Data type="word">Poison Resistance (AOS attribute)</Data>
        <Data type="word">Energy Resistance (AOS attribute)</Data>
        <Data type="word">Luck (AOS attribute)</Data>
        <Data type="word">Minimum Weapon Damage (AOS attribute)</Data>
